# Generated by Django 5.0.2 on 2024-02-24 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Localidades',
            fields=[
                ('id_localidad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_localidad', models.CharField(max_length=30, unique=True, verbose_name='Nombre localidad')),
            ],
            options={
                'verbose_name': 'Localidad',
                'verbose_name_plural': 'Localidades',
                'db_table': 'localidad',
                'ordering': ['id_localidad'],
            },
        ),
    ]
