# Generated by Django 5.0.2 on 2024-02-29 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulos',
            fields=[
                ('id_articulo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_articulo', models.CharField(max_length=30, unique=True)),
                ('cantidad_articulo', models.IntegerField()),
                ('dimensiones_articulo', models.CharField(blank=True, max_length=30, null=True)),
                ('descripcion_articulo', models.CharField(blank=True, max_length=100, null=True)),
                ('precio_articulo', models.DecimalField(decimal_places=5, max_digits=10)),
            ],
            options={
                'verbose_name': 'Articulo',
                'verbose_name_plural': 'Articulos',
                'db_table': 'articulos',
            },
        ),
        migrations.CreateModel(
            name='Barrios',
            fields=[
                ('id_barrio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_barrio', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name': 'Barrio',
                'verbose_name_plural': 'Barrios',
                'db_table': 'barrios',
            },
        ),
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=30, unique=True)),
                ('descuento_categoria', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'db_table': 'categorias',
            },
        ),
        migrations.CreateModel(
            name='Colores',
            fields=[
                ('id_color', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_color', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name': 'Color',
                'verbose_name_plural': 'Colores',
                'db_table': 'colores',
            },
        ),
        migrations.CreateModel(
            name='EntregaMateriales',
            fields=[
                ('id_entrega_material', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_entrega_material', models.DateTimeField()),
                ('cantidad_entrega_material', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Entrega material',
                'verbose_name_plural': 'Entregas materiales',
                'db_table': 'entrega_materiales',
            },
        ),
        migrations.CreateModel(
            name='EstadoPedido',
            fields=[
                ('id_estado_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_estado_pedido', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name': 'Estado pedido',
                'verbose_name_plural': 'Estado pedidos',
                'db_table': 'estado_pedido',
            },
        ),
        migrations.CreateModel(
            name='EstadosArticulos',
            fields=[
                ('id_estado_articulo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_estado_articulo', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name': 'Estado articulo',
                'verbose_name_plural': 'Estado articulos',
                'db_table': 'estados_articulos',
            },
        ),
        migrations.CreateModel(
            name='Estampados',
            fields=[
                ('id_estampado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=30, null=True)),
                ('imagen_url', models.TextField(unique=True)),
            ],
            options={
                'verbose_name': 'Estampado',
                'verbose_name_plural': 'Estampados',
                'db_table': 'estampados',
            },
        ),
        migrations.CreateModel(
            name='Localidades',
            fields=[
                ('id_localidad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_localidad', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name': 'Localidad',
                'verbose_name_plural': 'Localidades',
                'db_table': 'localidades',
            },
        ),
        migrations.CreateModel(
            name='MarcasVehiculos',
            fields=[
                ('id_marca_vehiculo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_marca_vehiculo', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name': 'Marca vehiculo',
                'verbose_name_plural': 'Marcas vehiculos',
                'db_table': 'marcas_vehiculos',
            },
        ),
        migrations.CreateModel(
            name='MetodoEntrega',
            fields=[
                ('id_metodo_entrega', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_metodo_entrega', models.CharField(max_length=30, unique=True)),
                ('costo_metodo_entrega', models.DecimalField(decimal_places=5, max_digits=10)),
            ],
            options={
                'verbose_name': 'Metodo entrega',
                'verbose_name_plural': 'Metodos de entregas',
                'db_table': 'metodo_entrega',
            },
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id_metodo_pago', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_metodo_pago', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name': 'Metodo pago',
                'verbose_name_plural': 'Metodos de pagos',
                'db_table': 'metodo_pago',
            },
        ),
        migrations.CreateModel(
            name='TiposArticulos',
            fields=[
                ('id_tipo_articulo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo_articulo', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name': 'tipo articulo',
                'verbose_name_plural': 'tipos articulos',
                'db_table': 'tipos_articulos',
            },
        ),
        migrations.CreateModel(
            name='TiposVehiculos',
            fields=[
                ('id_tipo_vehiculo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo_vehiculo', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name': 'tipo vehiculo',
                'verbose_name_plural': 'tipos vehiculos',
                'db_table': 'tipos_vehiculos',
            },
        ),
        migrations.CreateModel(
            name='Direcciones',
            fields=[
                ('id_direccion', models.AutoField(primary_key=True, serialize=False)),
                ('detalles', models.CharField(max_length=100)),
                ('barrio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='coreapp.barrios')),
            ],
            options={
                'verbose_name': 'Direccion',
                'verbose_name_plural': 'Direcciones',
                'db_table': 'direccion',
            },
        ),
        migrations.CreateModel(
            name='EntregasArticulos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='coreapp.articulos')),
                ('entrega_material', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='coreapp.entregamateriales')),
            ],
            options={
                'verbose_name': 'Entrega articulo',
                'verbose_name_plural': 'Entregas articulos',
                'db_table': 'entregas_articulos',
            },
        ),
        migrations.AddField(
            model_name='articulos',
            name='estado_articulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='coreapp.estadosarticulos'),
        ),
        migrations.AddField(
            model_name='barrios',
            name='localidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='coreapp.localidades'),
        ),
        migrations.CreateModel(
            name='ModelosVehiculos',
            fields=[
                ('id_modelo_vehiculo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_modelo_vehiculo', models.CharField(max_length=30, unique=True)),
                ('numero_modelo_vehiculo', models.IntegerField()),
                ('marca_vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='coreapp.marcasvehiculos')),
                ('tipo_vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='coreapp.tiposvehiculos')),
            ],
            options={
                'verbose_name': 'modelo vehiculo',
                'verbose_name_plural': 'Modelos vehiculos',
                'db_table': 'modelos_vehiculos',
            },
        ),
        migrations.CreateModel(
            name='OrdenPersonalizada',
            fields=[
                ('id_orden_personalizada', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion_orden_personalizada', models.DateTimeField()),
                ('base_antideslizante', models.BooleanField()),
                ('impermeable', models.BooleanField()),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='coreapp.colores')),
                ('color_borde', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ordenpersonalizada_color_borde_set', to='coreapp.colores')),
                ('estampado', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='coreapp.estampados')),
            ],
            options={
                'verbose_name': 'Orden Personalizada',
                'verbose_name_plural': 'Ordenes personalizadas',
                'db_table': 'orden_personalizada',
            },
        ),
        migrations.CreateModel(
            name='MaterialesOrdenPersonalizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='coreapp.articulos')),
                ('orden_personalizada', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='coreapp.ordenpersonalizada')),
            ],
            options={
                'verbose_name': 'Material orden personalizada',
                'verbose_name_plural': 'Materiales orden personalizadas',
                'db_table': 'materiales_orden_personalizada',
            },
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_entrega_pedido', models.TimeField()),
                ('precio_total_pedido', models.DecimalField(decimal_places=5, max_digits=10)),
                ('fecha_pago_pedido', models.DateTimeField()),
                ('estado_pedido', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='coreapp.estadopedido')),
                ('metodo_entrega', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='coreapp.metodoentrega')),
                ('metodo_pago', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='coreapp.metodopago')),
            ],
            options={
                'verbose_name': 'pedido',
                'verbose_name_plural': 'pedidos',
                'db_table': 'pedidos',
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('imagen_producto', models.TextField(unique=True)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='coreapp.articulos')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='coreapp.categorias')),
                ('modelo_vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='coreapp.modelosvehiculos')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
                'db_table': 'productos',
            },
        ),
        migrations.AddField(
            model_name='ordenpersonalizada',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='coreapp.productos'),
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id_detalle_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_solicitada', models.IntegerField()),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='coreapp.pedidos')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='coreapp.productos')),
            ],
            options={
                'verbose_name': 'Detalle pedido',
                'verbose_name_plural': 'Detalle pedidos',
                'db_table': 'detalle_pedido',
            },
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_proveedor', models.CharField(max_length=30, unique=True)),
                ('telefono_proveedor', models.CharField(max_length=10, unique=True)),
                ('email_proveedor', models.CharField(max_length=60, unique=True)),
                ('direccion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='coreapp.direcciones')),
            ],
            options={
                'verbose_name': 'proveedor',
                'verbose_name_plural': 'proveedores',
                'db_table': 'proveedores',
            },
        ),
        migrations.CreateModel(
            name='PreciosProveedor',
            fields=[
                ('id_precio_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('precio_proveedor', models.DecimalField(decimal_places=5, max_digits=10)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='coreapp.articulos')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='coreapp.proveedores')),
            ],
            options={
                'verbose_name': 'precio proveedor',
                'verbose_name_plural': 'precios proveedores',
                'db_table': 'precios_proveedor',
            },
        ),
        migrations.AddField(
            model_name='entregamateriales',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='coreapp.proveedores'),
        ),
        migrations.AddField(
            model_name='articulos',
            name='tipo_articulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='coreapp.tiposarticulos'),
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombres_usuario', models.CharField(max_length=30)),
                ('apellidos_usuario', models.CharField(max_length=30)),
                ('contrasenia', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=60, unique=True)),
                ('telefono', models.CharField(max_length=10, unique=True)),
                ('direccion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='coreapp.direcciones')),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
                'db_table': 'usuarios',
            },
        ),
        migrations.AddField(
            model_name='pedidos',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='coreapp.usuarios'),
        ),
        migrations.AddField(
            model_name='ordenpersonalizada',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='coreapp.usuarios'),
        ),
    ]
