# Generated by Django 5.0.2 on 2024-02-27 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulos',
            fields=[
                ('id_articulo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_articulo', models.CharField(max_length=30, unique=True)),
                ('cantidad_articulo', models.IntegerField()),
                ('dimensiones_articulo', models.CharField(blank=True, max_length=30, null=True)),
                ('descripcion_articulo', models.CharField(blank=True, max_length=100, null=True)),
                ('precio_articulo', models.DecimalField(decimal_places=5, max_digits=10)),
            ],
            options={
                'db_table': 'articulos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Barrios',
            fields=[
                ('id_barrio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_barrio', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'barrios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=30, unique=True)),
                ('descuento_categoria', models.IntegerField()),
            ],
            options={
                'db_table': 'categorias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Colores',
            fields=[
                ('id_color', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_color', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'colores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id_detalle_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_solicitada', models.IntegerField()),
            ],
            options={
                'db_table': 'detalle_pedido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Direcciones',
            fields=[
                ('id_direccion', models.AutoField(primary_key=True, serialize=False)),
                ('detalles', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'direcciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EntregaMateriales',
            fields=[
                ('id_entrega_material', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_entrega_material', models.DateTimeField()),
                ('cantidad_entrega_material', models.IntegerField()),
            ],
            options={
                'db_table': 'entrega_materiales',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EntregasArticulos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'entregas_articulos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoPedido',
            fields=[
                ('id_estado_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_estado_pedido', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'estado_pedido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadosArticulos',
            fields=[
                ('id_estado_articulo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_estado_articulo', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'estados_articulos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estampados',
            fields=[
                ('id_estampado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=30, null=True)),
                ('imagen_url', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'estampados',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id_localidad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_localidad', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'localidad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Localidades',
            fields=[
                ('id_localidad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_localidad', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'localidades',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MarcasVehiculos',
            fields=[
                ('id_marca_vehiculo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_marca_vehiculo', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'marcas_vehiculos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MaterialesOrdenPersonalizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'materiales_orden_personalizada',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MetodoEntrega',
            fields=[
                ('id_metodo_entrega', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_metodo_entrega', models.CharField(max_length=30, unique=True)),
                ('costo_metodo_entrega', models.DecimalField(decimal_places=5, max_digits=10)),
            ],
            options={
                'db_table': 'metodo_entrega',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id_metodo_pago', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_metodo_pago', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'metodo_pago',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModelosVehiculos',
            fields=[
                ('id_modelo_vehiculo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_modelo_vehiculo', models.CharField(max_length=30, unique=True)),
                ('numero_modelo_vehiculo', models.IntegerField()),
            ],
            options={
                'db_table': 'modelos_vehiculos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrdenPersonalizada',
            fields=[
                ('id_orden_personalizada', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion_orden_personalizada', models.DateTimeField()),
                ('base_antideslizante', models.BooleanField()),
                ('impermeable', models.BooleanField()),
            ],
            options={
                'db_table': 'orden_personalizada',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_entrega_pedido', models.TimeField()),
                ('precio_total_pedido', models.DecimalField(decimal_places=5, max_digits=10)),
                ('fecha_pago_pedido', models.DateTimeField()),
            ],
            options={
                'db_table': 'pedidos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PreciosProveedor',
            fields=[
                ('id_precio_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('precio_proveedor', models.DecimalField(decimal_places=5, max_digits=10)),
            ],
            options={
                'db_table': 'precios_proveedor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('imagen_producto', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'productos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_proveedor', models.CharField(max_length=30, unique=True)),
                ('telefono_proveedor', models.CharField(max_length=10, unique=True)),
                ('email_proveedor', models.CharField(max_length=60, unique=True)),
            ],
            options={
                'db_table': 'proveedores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TiposArticulos',
            fields=[
                ('id_tipo_articulo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo_articulo', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'tipos_articulos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TiposVehiculos',
            fields=[
                ('id_tipo_vehiculo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo_vehiculo', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'tipos_vehiculos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombres_usuario', models.CharField(max_length=30)),
                ('apellidos_usuario', models.CharField(max_length=30)),
                ('contrasenia', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=60, unique=True)),
                ('telefono', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
    ]
